random_forest:
  random_state: 42

grid_search:
  cv: 5
  scoring: 'neg_mean_squared_error'
  return_train_score: True

param_grid:
  - n_estimators: [3, 10, 30]
    max_features: [2, 4, 6, 8]
  - bootstrap: [False]
    n_estimators: [3, 10]
    max_features: [2, 3, 4]
